ntp_reference_clocks = ["0-0,time.facebook.com:123"]
local_address = "1-ff00:0:111,10.1.1.11:123"

ntske_cert_file = "./testnet/gen/tls.crt"
ntske_key_file = "./testnet/gen/tls.key"
ntske_server_name = "localhost"
